### ISSUE TITLE
Questions about DDXPlus

### ISSUE THREAD

**Issue by guosyjlu** [stream-bench/stream-bench#15]
Hi, thanks for the outstanding work on this project!

I am currently working on scaling the DDXPlus dataset within StreamBench for validation. However, I am encountering some difficulties in converting the DDXPlus dataset, which is originally in raw csv format, to the format required by StreamBench.

Could you please provide some guidance or the script on how to perform this conversion? Thank you in advance for your assistance!

**Comment by Brian-Ckwu** [comment]
Hello, @guosyjlu. Can you specify the issue you encounter by providing an actual example?

By the way, you may lookup our HuggingFace page for the desired format of DDXPlus: https://huggingface.co/datasets/appier-ai-research/StreamBench/viewer/ddxplus

**Comment by guosyjlu** [comment]
Yeah, I mean the dataset in the original DDXPlus is in csv format, like:
> {
    "AGE": 18,
    "DIFFERENTIAL_DIAGNOSIS": [["Bronchitis", 0.19171203430383882], ["Pneumonia", 0.17579340398940366], ["URTI", 0.1607809719801254], ["Bronchiectasis", 0.12429044460990353], ["Tuberculosis", 0.11367177304035844], ["Influenza", 0.11057936110639896], ["HIV (initial infection)", 0.07333003867293564], ["Chagas", 0.04984197229703562]],
    "SEX": "M",
    "PATHOLOGY": "URTI",
    "EVIDENCES": ["E_48", "E_50", "E_53", "E_54_@_V_161", "E_54_@_V_183", "E_55_@_V_89", "E_55_@_V_108", "E_55_@_V_167", "E_56_@_4", "E_57_@_V_123", "E_58_@_3", "E_59_@_3", "E_77", "E_79", "E_91", "E_97", "E_201", "E_204_@_V_10", "E_222"],
    "INITIAL_EVIDENCE": "E_91"
}

How to convert the original dataset of DDXPlus to the format in StreamBench as below?
> Sex: Female, Age: 53 - I have severe Chronic Obstructive Pulmonary Disease (COPD). - I am experiencing shortness of breath or difficulty breathing in a significant way. - I have had one or several flare ups of chronic obstructive pulmonary disease (COPD) in the past year. - I have a cough that produces colored or more abundant sputum than usual. - I smoke cigarettes. - I have been diagnosed with gastroesophageal reflux. - I work in agriculture. - I have a cough.

**Comment by Brian-Ckwu** [comment]
Hi @guosyjlu , I see! You may refer to my other repo https://github.com/Brian-Ckwu/dr-cot and use the preprocessing script. Feel free to let me know if you still encounter other issues.

**Comment by guosyjlu** [comment]
Thanks you so much for your help!
